spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/polinizamap
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  jackson:
    default-property-inclusion: non_null

server:
  port: 8080

jwt:
  key: ${JWT_KEY:zJM#adyQBKDMSRoPcNy6GX1&!9b5y69K##1i8iao8e-Bz9InR&$Gfludfmd2DkV5pZN2Wx#V&d5IE=d7D&XD-HCOZx00tkdvHr5=NoGaCCQD1Rm-e9kpAhpxv$2H4aES&8gCSq0uny8IAx53#1brQ9WWj8ukzbid!Qnel3scc9Jjo9m=b=jNxKfdViPaJ2MWeilrsn6GziIHCB9ztRGsZ2&VA&=Xi17j&AhrfZ71SBxYi9mv_ZWhmt!JwpodcAx$dUjTa4rzpjws4F#-KsQ&2kAqlZKy_E5Htwk=Aq7PYJI26HTLHap47B_xEgeKLhiNfKFTcbZy40CEXghDAeZlc3Vc}
  expiration: 86400000 # 24h

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs